# Generated by Django 2.1.2 on 2018-10-20 01:14

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from gallery.models import Photo

def add_groups(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(Photo)
    permission = Permission.objects.create(
        codename='approve_photo',
        name='Can approve photos to be published',
        content_type=content_type,
    )
    
    #friends
    friends, created = Group.objects.get_or_create(name='friends')   

    #couple
    couple, created = Group.objects.get_or_create(name='couple')   
    couple.permissions.add(permission)

'''
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from api.models import Project
new_group, created = Group.objects.get_or_create(name='new_group')

# Now what - Say I want to add 'Can add project' permission to new_group?
permission = Permission.objects.create(codename='gallery.approve_photo',
                                   name='Can add project',
                                   content_type=ct)
new_group.permissions.add(permission)
'''

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
