# Generated by Django 2.1.2 on 2018-10-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s3url',
            field=models.URLField(default=''),
        ),
    ]
