# Generated by Django 2.1.2 on 2018-10-20 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
